### ISSUE TITLE
Testing and warning fixing

### ISSUE THREAD

**Issue by dricki** [iris-edu/evalresp#12]
- Use existing tests to do testing on modern Linux, Windows, macOS
- Make sure that there is no compiler warnings from current versions of GCC, clang/llvm and MSVC compilers on, at least, the equivalent of “-Wall” level reporting. 
- The previous task is probably becoming feasible only when we do other tasks (splining, creating lib API, etc.). However in preparation for this warning bashing we need to make sure we have VMs which do build evalresp via clang/llvm and MSVC compilers.

**Comment by rcasey-iris** [comment]
This is an old issue and 5.0.0 has been released in 2019.  Let's close this issue and it will set the 5.0.0 milestone to 100%.
